"""base: utenti, anagrafica, import, audit

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 12:24:23.470054
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=50), nullable=True),
    sa.Column('nominativo', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('telefono_cellulare', sa.String(length=30), nullable=True),
    sa.Column('telefono_fisso', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('escluso_richiami', sa.Boolean(), nullable=False),
    sa.Column('consenso_contatto', sa.Boolean(), nullable=True),
    sa.Column('extra', postgresql.JSONB(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice')
    )
    op.create_index(op.f('ix_cliente_nominativo'), 'cliente', ['nominativo'], unique=False)
    op.create_index(op.f('ix_cliente_telefono_cellulare'), 'cliente', ['telefono_cellulare'], unique=False)
    op.create_index(op.f('ix_cliente_telefono_fisso'), 'cliente', ['telefono_fisso'], unique=False)
    op.create_table('mappatura_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('intestazioni', postgresql.JSONB(), nullable=False),
    sa.Column('mappatura', postgresql.JSONB(), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('sede',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('utente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ruolo', sa.String(length=20), nullable=False),
    sa.Column('origine', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('interno', sa.String(length=20), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('tentativi_falliti', sa.Integer(), nullable=False),
    sa.Column('bloccato_fino', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_accesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('azione', sa.String(length=50), nullable=False),
    sa.Column('oggetto', sa.String(length=200), nullable=True),
    sa.Column('dettaglio', postgresql.JSONB(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('quando', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_azione'), 'audit', ['azione'], unique=False)
    op.create_index(op.f('ix_audit_quando'), 'audit', ['quando'], unique=False)
    op.create_table('importazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('nome_file', sa.String(length=300), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('intestazioni', postgresql.JSONB(), nullable=False),
    sa.Column('mappatura', postgresql.JSONB(), nullable=True),
    sa.Column('righe_totali', sa.Integer(), nullable=False),
    sa.Column('clienti_nuovi', sa.Integer(), nullable=False),
    sa.Column('clienti_aggiornati', sa.Integer(), nullable=False),
    sa.Column('veicoli_nuovi', sa.Integer(), nullable=False),
    sa.Column('veicoli_aggiornati', sa.Integer(), nullable=False),
    sa.Column('passaggi_nuovi', sa.Integer(), nullable=False),
    sa.Column('righe_scartate', sa.Integer(), nullable=False),
    sa.Column('errori', postgresql.JSONB(), nullable=False),
    sa.Column('creato_da_id', sa.Integer(), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completato_il', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creato_da_id'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veicolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('targa', sa.String(length=20), nullable=True),
    sa.Column('telaio', sa.String(length=30), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modello', sa.String(length=200), nullable=True),
    sa.Column('tipologia', sa.String(length=100), nullable=True),
    sa.Column('data_immatricolazione', sa.Date(), nullable=True),
    sa.Column('data_ultimo_passaggio', sa.Date(), nullable=True),
    sa.Column('extra', postgresql.JSONB(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telaio')
    )
    op.create_index(op.f('ix_veicolo_cliente_id'), 'veicolo', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_veicolo_data_immatricolazione'), 'veicolo', ['data_immatricolazione'], unique=False)
    op.create_index(op.f('ix_veicolo_data_ultimo_passaggio'), 'veicolo', ['data_ultimo_passaggio'], unique=False)
    op.create_index(op.f('ix_veicolo_marca'), 'veicolo', ['marca'], unique=False)
    op.create_index(op.f('ix_veicolo_targa'), 'veicolo', ['targa'], unique=False)
    op.create_table('import_riga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importazione_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('dati', postgresql.JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['importazione_id'], ['importazione.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_riga_importazione_id'), 'import_riga', ['importazione_id'], unique=False)
    op.create_table('passaggio_officina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veicolo_id', sa.Integer(), nullable=False),
    sa.Column('numero_or', sa.String(length=50), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('data_apertura', sa.Date(), nullable=True),
    sa.Column('data_chiusura', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sede.id'], ),
    sa.ForeignKeyConstraint(['veicolo_id'], ['veicolo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_or')
    )
    op.create_index(op.f('ix_passaggio_officina_veicolo_id'), 'passaggio_officina', ['veicolo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passaggio_officina_veicolo_id'), table_name='passaggio_officina')
    op.drop_table('passaggio_officina')
    op.drop_index(op.f('ix_import_riga_importazione_id'), table_name='import_riga')
    op.drop_table('import_riga')
    op.drop_index(op.f('ix_veicolo_targa'), table_name='veicolo')
    op.drop_index(op.f('ix_veicolo_marca'), table_name='veicolo')
    op.drop_index(op.f('ix_veicolo_data_ultimo_passaggio'), table_name='veicolo')
    op.drop_index(op.f('ix_veicolo_data_immatricolazione'), table_name='veicolo')
    op.drop_index(op.f('ix_veicolo_cliente_id'), table_name='veicolo')
    op.drop_table('veicolo')
    op.drop_table('importazione')
    op.drop_index(op.f('ix_audit_quando'), table_name='audit')
    op.drop_index(op.f('ix_audit_azione'), table_name='audit')
    op.drop_table('audit')
    op.drop_table('utente')
    op.drop_table('sede')
    op.drop_table('mappatura_import')
    op.drop_index(op.f('ix_cliente_telefono_fisso'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_telefono_cellulare'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_nominativo'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
