"""fase 2: team, elenchi, campagne, contatti, chiamate, note, opportunita, impostazioni

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 13:39:45.688225
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impostazione',
    sa.Column('chiave', sa.String(length=50), nullable=False),
    sa.Column('valore', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chiave')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('voce_elenco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elenco', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('effetto', sa.String(length=20), nullable=True),
    sa.Column('famiglia', sa.String(length=200), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elenco', 'nome')
    )
    op.create_index(op.f('ix_voce_elenco_elenco'), 'voce_elenco', ['elenco'], unique=False)
    op.create_table('campagna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('motivo_id', sa.Integer(), nullable=True),
    sa.Column('filtri', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('creato_da_id', sa.Integer(), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chiusa_il', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creato_da_id'], ['utente.id'], ),
    sa.ForeignKeyConstraint(['motivo_id'], ['voce_elenco.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campagna_team_id'), 'campagna', ['team_id'], unique=False)
    op.create_table('team_membro',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'utente_id')
    )
    op.create_index(op.f('ix_team_membro_utente_id'), 'team_membro', ['utente_id'], unique=False)
    op.create_table('contatto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campagna_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veicolo_id', sa.Integer(), nullable=False),
    sa.Column('operatore_id', sa.Integer(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('priorita', sa.Integer(), nullable=False),
    sa.Column('data_richiamo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentativi', sa.Integer(), nullable=False),
    sa.Column('ultimo_esito_id', sa.Integer(), nullable=True),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campagna_id'], ['campagna.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['operatore_id'], ['utente.id'], ),
    sa.ForeignKeyConstraint(['ultimo_esito_id'], ['voce_elenco.id'], ),
    sa.ForeignKeyConstraint(['veicolo_id'], ['veicolo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campagna_id', 'veicolo_id')
    )
    op.create_index(op.f('ix_contatto_campagna_id'), 'contatto', ['campagna_id'], unique=False)
    op.create_index(op.f('ix_contatto_cliente_id'), 'contatto', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contatto_operatore_id'), 'contatto', ['operatore_id'], unique=False)
    op.create_index(op.f('ix_contatto_stato'), 'contatto', ['stato'], unique=False)
    op.create_index(op.f('ix_contatto_veicolo_id'), 'contatto', ['veicolo_id'], unique=False)
    op.create_table('chiamata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contatto_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('operatore_id', sa.Integer(), nullable=False),
    sa.Column('direzione', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('inizio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('durata_secondi', sa.Integer(), nullable=True),
    sa.Column('esito_id', sa.Integer(), nullable=True),
    sa.Column('unique_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['contatto_id'], ['contatto.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['esito_id'], ['voce_elenco.id'], ),
    sa.ForeignKeyConstraint(['operatore_id'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chiamata_cliente_id'), 'chiamata', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_chiamata_contatto_id'), 'chiamata', ['contatto_id'], unique=False)
    op.create_index(op.f('ix_chiamata_inizio'), 'chiamata', ['inizio'], unique=False)
    op.create_index(op.f('ix_chiamata_operatore_id'), 'chiamata', ['operatore_id'], unique=False)
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('chiamata_id', sa.Integer(), nullable=True),
    sa.Column('autore_id', sa.Integer(), nullable=False),
    sa.Column('testo', sa.Text(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autore_id'], ['utente.id'], ),
    sa.ForeignKeyConstraint(['chiamata_id'], ['chiamata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nota_cliente_id'), 'nota', ['cliente_id'], unique=False)
    op.create_table('opportunita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolare_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veicolo_id', sa.Integer(), nullable=True),
    sa.Column('chiamata_id', sa.Integer(), nullable=True),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('data_appuntamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('ammontare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vendita_aggiuntiva', sa.Boolean(), nullable=False),
    sa.Column('prezzo_vendita', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prodotto_id', sa.Integer(), nullable=True),
    sa.Column('motivo_perdita_id', sa.Integer(), nullable=True),
    sa.Column('note_perdita', sa.Text(), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chiamata_id'], ['chiamata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['voce_elenco.id'], ),
    sa.ForeignKeyConstraint(['motivo_perdita_id'], ['voce_elenco.id'], ),
    sa.ForeignKeyConstraint(['prodotto_id'], ['voce_elenco.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sede.id'], ),
    sa.ForeignKeyConstraint(['titolare_id'], ['utente.id'], ),
    sa.ForeignKeyConstraint(['veicolo_id'], ['veicolo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunita_cliente_id'), 'opportunita', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_opportunita_data_appuntamento'), 'opportunita', ['data_appuntamento'], unique=False)
    op.create_index(op.f('ix_opportunita_fase_id'), 'opportunita', ['fase_id'], unique=False)
    op.create_index(op.f('ix_opportunita_titolare_id'), 'opportunita', ['titolare_id'], unique=False)
    op.create_table('opportunita_fase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunita_id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('quando', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fase_id'], ['voce_elenco.id'], ),
    sa.ForeignKeyConstraint(['opportunita_id'], ['opportunita.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['utente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunita_fase_opportunita_id'), 'opportunita_fase', ['opportunita_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunita_fase_opportunita_id'), table_name='opportunita_fase')
    op.drop_table('opportunita_fase')
    op.drop_index(op.f('ix_opportunita_titolare_id'), table_name='opportunita')
    op.drop_index(op.f('ix_opportunita_fase_id'), table_name='opportunita')
    op.drop_index(op.f('ix_opportunita_data_appuntamento'), table_name='opportunita')
    op.drop_index(op.f('ix_opportunita_cliente_id'), table_name='opportunita')
    op.drop_table('opportunita')
    op.drop_index(op.f('ix_nota_cliente_id'), table_name='nota')
    op.drop_table('nota')
    op.drop_index(op.f('ix_chiamata_operatore_id'), table_name='chiamata')
    op.drop_index(op.f('ix_chiamata_inizio'), table_name='chiamata')
    op.drop_index(op.f('ix_chiamata_contatto_id'), table_name='chiamata')
    op.drop_index(op.f('ix_chiamata_cliente_id'), table_name='chiamata')
    op.drop_table('chiamata')
    op.drop_index(op.f('ix_contatto_veicolo_id'), table_name='contatto')
    op.drop_index(op.f('ix_contatto_stato'), table_name='contatto')
    op.drop_index(op.f('ix_contatto_operatore_id'), table_name='contatto')
    op.drop_index(op.f('ix_contatto_cliente_id'), table_name='contatto')
    op.drop_index(op.f('ix_contatto_campagna_id'), table_name='contatto')
    op.drop_table('contatto')
    op.drop_index(op.f('ix_team_membro_utente_id'), table_name='team_membro')
    op.drop_table('team_membro')
    op.drop_index(op.f('ix_campagna_team_id'), table_name='campagna')
    op.drop_table('campagna')
    op.drop_index(op.f('ix_voce_elenco_elenco'), table_name='voce_elenco')
    op.drop_table('voce_elenco')
    op.drop_table('team')
    op.drop_table('impostazione')
    # ### end Alembic commands ###
